apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: gitops-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: nginx:1.28
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: gitops-lab
spec:
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 80
